### ISSUE TITLE
App crash in release mode

### ISSUE THREAD

**Issue by dosthub** [mrtungdev/flutter_epson_epos#1]
The app is getting closed automatically when we launch the app (Release mode)

**Comment by mrtungdev** [comment]
Could you provide more detail?

**Comment by dosthub** [comment]
I have create a new app and used the example which is mentioned in pub.dev. 
the app is working fine in debug mode. but when I have generated the release build, the app is getting closed by itself.

And Can you please give the example for styling text and image usage.

**Comment by dosthub** [comment]
Can you please give us the usage of the package. It will be very helpful.

Thanks for the package 👍

**Comment by mrtungdev** [comment]
Currently, this package is not recommended for Production. I'll create docs next time.

> the app is working fine in debug mode. but when I have generated the release build, the app is getting closed by itself.

Could you provide your env, android device, os?

> And Can you please give the example for styling text and image usage.

To add the image you can call the command: `appendBitmap`
I'll implement `addTextStyle` in the next version.

Thank you

**Comment by dosthub** [comment]
> Currently, this package is not recommended for Production. I'll create docs next time.
> 
> > the app is working fine in debug mode. but when I have generated the release build, the app is getting closed by itself.
> 
> Could you provide your env, android device, os?
> 
> > And Can you please give the example for styling text and image usage.
> 
> To add the image you can call the command: `appendBitmap`
> I'll implement `addTextStyle` in the next version.
> 
> Thank you


I'm trying on android devices.
Thank you

**Comment by source-creator** [comment]
The issue seems to be caused because ProGuard is not setup to exclude the library files.  

A workaround is to add the following to this file: `./example/android/app/build.gradle`
```
android {
    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
```

@dosthub
